#ifndef REDMINE_CONFIG_H
#define REDMINE_CONFIG_H

#cmakedefine REDMINE_PLATFORM_LINUX ${REDMINE_PLATFORM_LINUX}

#cmakedefine REDMINE_PLATFORM_MAC ${REDMINE_PLATFORM_MAC}

#cmakedefine REDMINE_PLATFORM_WINDOWS ${REDMINE_PLATFORM_WINDOWS}

#cmakedefine REDMINE_DEBUG ${REDMINE_DEBUG}

#endif
